// This file was generated by sqts. Do not edit this file directly.

import type { User } from "./";
import { execute as __sqtsExecute } from "./index.ts";

type QueryProps = { id: string; };

export default async function execGetUserQuery({ id }: QueryProps): Promise<QueryOutput> {
    const query = `SELECT u.id AS "users[].id", u.email AS "users[].email" FROM users u
WHERE u.id = ?;`;
    const params = [id];
    const output = await __sqtsExecute(query, params, { queryName: "getUser", sourceFile: "getUser.sqts" });
    const rows: Record<string, unknown>[] = output.rows as Record<string, unknown>[];
    const mappings = [
            { aliasKey: "users[].id", targetPath: ["id"] },
            { aliasKey: "users[].email", targetPath: ["email"] },
        ] as const;
    const users: QueryOutput = [];
    for (const row of rows) {
        const value = {} as QueryOutput[number];
        for (const mapping of mappings) {
            let current: Record<string, any> = value as Record<string, any>;
            const path = mapping.targetPath;
            for (let i = 0; i < path.length - 1; i++) {
                const key = path[i]!;
                const existing = current[key];
                if (typeof existing !== "object" || existing === null || Array.isArray(existing)) {
                    current[key] = {};
                }

                current = current[key] as Record<string, any>;
            }

            current[path[path.length - 1]!] = row[mapping.aliasKey];
        }

        users.push(value);
    }

    return users;
}

type QueryOutput = User[];