import { resolve } from "path";
import type { Project } from "ts-morph";

import type { CompileContext } from "@/compiler/getCompileContext.ts";
import { schemaColumnToType } from "@/compiler/lib/schemaColumnToType.ts";
import { tableNameToTypeName } from "@/compiler/lib/tableNameToTypeName.ts";

export async function compileModelTypes(
    tsProj: Project,
    outdir: string,
    ctx: CompileContext,
) {
    const outputPath = resolve(outdir, "types.ts");
    const outputFile = tsProj.createSourceFile(outputPath, "", {
        overwrite: true,
    });

    outputFile.addStatements("// This file is auto-generated by SQTS.");
    outputFile.addStatements("// Do not edit manually.");
    outputFile.addStatements("");

    const resolvedNames = new Map<string, string>();

    for (const tableKey of ctx.schema.tableOrder) {
        const table = ctx.schema.tables[tableKey];
        if (!table) {
            throw new Error(
                `Schema invariant violation: table key "${tableKey}" was not found in schema.tables.`,
            );
        }

        if (table.schema !== "main") {
            throw new Error(
                `Unsupported schema "${table.schema}" for table "${table.key}". SQTS currently supports only the "main" schema for model generation.`,
            );
        }

        const typeName = tableNameToTypeName(table.name);
        const existingTableKey = resolvedNames.get(typeName);
        if (existingTableKey) {
            throw new Error(
                `Model type name collision: "${typeName}" resolves from both "${existingTableKey}" and "${table.key}".`,
            );
        }
        resolvedNames.set(typeName, table.key);

        outputFile.addInterface({
            isExported: true,
            name: typeName,
            properties: table.columnOrder.map((columnName) => {
                const column = table.columns[columnName];
                if (!column) {
                    throw new Error(
                        `Schema invariant violation: column "${columnName}" was not found in table "${table.key}".`,
                    );
                }

                return {
                    name: column.name,
                    type: schemaColumnToType(column.affinity, column.nullable),
                };
            }),
        });
        outputFile.addStatements("");
    }

    outputFile.organizeImports();
    outputFile.fixUnusedIdentifiers();
    outputFile.formatText();
}
