// This file is auto-generated by SQTS.
// Do not edit manually.
export interface User {
    id: number;
    name: string;
    email: string;
}

export interface Post {
    id: number;
    user_id: number;
    title: string;
    content: string;
    created_at: number | null;
}
