name: Housekeeping
on:
  push:
    branches: [beta]
  pull_request:
    branches: [beta]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun run build
      - run: bun test
      - run: bun install # make sure dist folder is properly linked to example
      - run: bun run --cwd example codegen
      - run: bun run --cwd example index.ts
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun run lint